version: "3.5"
services:
  rabbitmq1:
    image: rabbitmq:management
    ports:
      - "15672:15672"
      - "5672:5672"
      - "5671:5671"
      - "4369:4369"
    network_mode: "host"
    volumes:
      - $PWD/conf/rabbitmq/.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
      - $PWD/conf/rabbit-1/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - $PWD/rabbitmq_data-1:/var/lib/rabbitmq
      - $PWD/rabbitmq_definitions.json:/etc/rabbitmq/rabbitmq_definitions.json
    environment:
      - RABBITMQ_CONFIG_FILE=/etc/rabbitmq/rabbitmq.conf
    stop_grace_period: 1m
